# ========================== НАСТРОЙКИ ИГРЫ ==========================

STARTING_HEIGHT_RANDOM = False
STARTING_CIRCLES_COUNT = 5
WIDTH, HEIGHT = 854, 480
DEFAULT_CIRCLE_RADIUS = 20
DEFAULT_SPEED = 5

DEFAULT_MODE_COLOR = (0, 0, 255)
HARD_MODE_COLOR = (200, 0, 0)
EXTREME_MODE_COLOR = (100, 0, 100)
DEFAULT_CIRCLE_COLOR = (0, 0, 255)
START_RESPAWN_CIRCLES = True
SHOW_FINGER_POINT = True

HARD_MODE_STARTING_POINT = 50
EXTREME_MODE_STARTING_POINT = 100
HINDERS_STARTING_POINT = 120
DIAGONAL_HINDERS_STARTING_POINT = 150

MAX_HAMSTERS = 1
MAX_HINDERS = 1
MAX_DIAGONAL_HINDERS = 2

GOD_MODE = False

score = 0

HARD_MODE_IMAGE_MAX_INTENSITY = 50

EXTREME_MODE_IMAGE_INTENSITY_CHANGE_SPEED = 5
EXTREME_MODE_IMAGE_INTENSITY_CHANGE_SIGN_DEFAULT = 1
EXTREME_MODE_IMAGE_DEFAULT_INTENSITY = 50
EXTREME_MODE_IMAGE_MIN_INTENSITY = 50
EXTREME_MODE_IMAGE_MAX_INTENSITY = 120

HAMSTER_SPAWN_CHANCE = 15

# =====================================================================